version: "3"
services:
  server:
    build: ./server
    depends_on:
      - db
    ports:
      - "5000:5000"
    container_name: server-api
  client:
    build: ./client
    ports:
      - "80:80"
    container_name: client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: todo-db